<a href="https://colab.research.google.com/github/Pranayshukla0610/Python_Projects/blob/main/Python_Basics.ipynb" target="_parent"><img src="https://colab.research.google.com/assets/colab-badge.svg" alt="Open In Colab"/></a>

In [1]:
import sys

print("="*50)
print("Python Version")
print(sys.version)
print("="*50)

Python Version
3.12.13 (main, Mar  4 2026, 09:23:07) [GCC 11.4.0]


In [2]:
!pip -q install pandas numpy matplotlib seaborn torch torchvision

In [3]:
import os
import gc
import math
import random

import pandas as pd
import numpy as np
import matplotlib.pyplot as plt

import torch

In [4]:
SEED = 42
random.seed(SEED)

np.random.seed(SEED)

torch.manual_seed(SEED)

print("Seed Fixed")

Seed Fixed


In [5]:
def clear_memory():
  gc.collect()
  if torch.cuda.is_available():
    torch.cuda.empty_cache()

print("Memory Cleaned Successfully")

Memory Cleaned Successfully


In [6]:
device = 'cuda' if torch.cuda.is_available() else 'cpu'
print("Running on:",device)

Running on: cpu


In [7]:
age = 23
salary = 2500000
name = "Pranay"
is_student = True
print(age)
print(salary)
print(name)
print(is_student)

23
2500000
Pranay
True


In [8]:
print(type(age))
print(type(salary))
print(type(name))
print(type(is_student))

<class 'int'>
<class 'int'>
<class 'str'>
<class 'bool'>


In [10]:
name = "Generative AI"

print(name.upper())
print(name.lower())
print(name.replace("AI", "Engineer"))
print(name.title())
print(len(name))

GENERATIVE AI
generative ai
Generative Engineer
Generative Ai
13


In [11]:
a = 20
b = 8

print(a+b)
print(a-b)
print(a*b)
print(a//b)
print(a/b)
print(a%b)
print(a**2)

28
12
160
2
2.5
4
400


In [12]:
print(a>b)
print(a<b)
print(a==b)
print(a!=b)
print(a>=b)
print(a<=b)

True
False
False
True
True
False


In [14]:
numbers = [10,20,30,40,50,60,70,80,90]
print(numbers)
numbers.append(55)
numbers.remove(60)
print(numbers.insert(1,100))

[10, 20, 30, 40, 50, 60, 70, 80, 90]
None


In [15]:
print(numbers[:3])
print(numbers[2:])
print(numbers[::-1])

[10, 100, 20]
[20, 30, 40, 50, 70, 80, 90, 55]
[55, 90, 80, 70, 50, 40, 30, 20, 100, 10]


In [16]:
coordinates = (20,30)

print(coordinates)
print(coordinates[0])
print(coordinates[1])

(20, 30)
20
30


In [17]:
A = {1,2,3,4,5}
B = {3,4,5,6,7}

print(A.union(B))
print(A.intersection(B))
print(A.difference(B))

{1, 2, 3, 4, 5, 6, 7}
{3, 4, 5}
{1, 2}


In [18]:
student = {
    "Name":'Pranay Shukla',
    "Age": 26,
    "CGPA": 7.2
}
print(student)
print(student['Name'])
student['College'] = "JAGSoM"
print(student)

{'Name': 'Pranay Shukla', 'Age': 26, 'CGPA': 7.2}
Pranay Shukla
{'Name': 'Pranay Shukla', 'Age': 26, 'CGPA': 7.2, 'College': 'JAGSoM'}


In [19]:
marks = 81
if marks >= 90:
  print("Grade A")
elif marks >=80:
  print("Grade B")
elif marks >= 70:
  print("Grade C")
else:
  print("Grade D")

Grade B


In [21]:
for i in range(10):
  print(i)

0
1
2
3
4
5
6
7
8
9


In [22]:
count = 1
while count <= 5:
  print(count)
  count+=1

1
2
3
4
5


In [23]:
squares = [i*i for i in range(10)]
print(squares)

[0, 1, 4, 9, 16, 25, 36, 49, 64, 81]


In [24]:
def squares(x):
  return x*x

print(squares(10))

100


In [25]:
cube = lambda x:x**3
print(cube(3))

27


In [26]:
try:
  x = 10/0
except ZeroDivisionError:
  print("Cannot Divide by Zero")

Cannot Divide by Zero


In [28]:
class Student:
  def __init__(self,name,age):
    self.name = name
    self.age = age

  def introduce(self):
    print(f"My Name is {self.name}")

student = Student("Pranay",23)
student.introduce()

My Name is Pranay


In [29]:
array = np.array([1,2,3,4,5])

print(array)
print(type(array))

[1 2 3 4 5]
<class 'numpy.ndarray'>


In [30]:
print(array.shape)
print(array.ndim)
print(array.dtype)
print(array.size)

(5,)
1
int64
5


In [31]:
zeros = np.zeros((3,3))
ones = np.ones((3,3))
identity = np.eye(4)

print(zeros)
print()
print(ones)
print()
print(identity)

[[0. 0. 0.]
 [0. 0. 0.]
 [0. 0. 0.]]

[[1. 1. 1.]
 [1. 1. 1.]
 [1. 1. 1.]]

[[1. 0. 0. 0.]
 [0. 1. 0. 0.]
 [0. 0. 1. 0.]
 [0. 0. 0. 1.]]


In [32]:
np.random.seed(42)

In [33]:
a = np.array([1,2,3,4,5])

b = np.array([
    [1,2,3],
    [4,5,6]
])

c = np.array([
    [
        [1,2],
        [3,4]
    ],
    [
        [5,6],
        [7,8]
    ]
])

print(a)
print()
print(b)
print()
print(c)
print()

[1 2 3 4 5]

[[1 2 3]
 [4 5 6]]

[[[1 2]
  [3 4]]

 [[5 6]
  [7 8]]]



In [34]:
print("Shape :", b.shape)

print("Dimensions :", b.ndim)

print("Size :", b.size)

print("Datatype :", b.dtype)

print("Item Size :", b.itemsize)

print("Total Bytes :", b.nbytes)

Shape : (2, 3)
Dimensions : 2
Size : 6
Datatype : int64
Item Size : 8
Total Bytes : 48


In [37]:
print(a.dtype)

int64


In [38]:
print("Shape :", b.shape)

print("Dimensions :", b.ndim)

print("Size :", b.size)

print("Datatype :", b.dtype)

print("Item Size :", b.itemsize)

print("Total Bytes :", b.nbytes)

Shape : (2, 3)
Dimensions : 2
Size : 6
Datatype : int64
Item Size : 8
Total Bytes : 48
